### ISSUE TITLE
Complete dish database model and modify API accordingly

### ISSUE THREAD

**Issue by rhefner1** [cookomatic/cookomatic-api#13]
Look at [Dish Specification](https://docs.google.com/document/d/1qxJDtp8f7cKz7icmedTUxAnMT1pTP0ZgqTKpRWjNBO8/edit) document and fill out the data model in `cookomatic_api/db/*.py`. Update `api.py` accordingly to accept the right inputs and return the right outputs.

---
**Acceptance Test**: Demonstrate cURL calls to save a dish with a number of inputs and retrieve it.

**Comment by AninOnin** [comment]
Update dish.py data fields for dishes. We have name, we need
- ID
- tags
- ingredients list
- tools list
- prep list
- steps (should be a separate file, steps.py)
- total time
- number of servings

Possible fields for helpful tips, photos, and owner username (if recipe was uploaded by a user).
